### ISSUE TITLE
JSON Parse Error when function contains logging

### ISSUE THREAD

**Issue by patrickhousley** [lambci/docker-lambda#16]
When the lambda function being tested contains logging, JS runner incorrectly attempts to JSON.parse the entire stdout.

**Comment by mhart** [comment]
When you say "contains logging" – you must mean when the lambda function has written directly to `process.stdout`, correct? Because all `console.log`, and Lambda logs, are intercepted: https://github.com/lambci/docker-lambda/blob/master/nodejs4.3/run/awslambda-mock.js#L16-L22

This was a deliberate decision, considering it's the most straightforward way to communicate from a docker container – the only other option would be to communicate over sockets or similar, which would require a lot more setup.

So just to confirm you're writing directly to `process.stdout`, and it's not some bug in `console.log`?

**Comment by patrickhousley** [comment]
@mhart Thanks for the comments here and on the PR. I am using Winston logger to do all my logging. Let me dig a bit more now that I have had a few hours of sleep.

**Comment by patrickhousley** [comment]
Looks like your assumption was correct. Winston logs directly to stdout. https://github.com/winstonjs/winston/blob/master/lib/winston/transports/console.js#L121 I will address the comments on the PR.
