### ISSUE TITLE
OpenSSL version incorrect in build images

### ISSUE THREAD

**Issue by jaikdean** [lambci/docker-lambda#163]
Non-build environments have the correct 1.0.1k version:

```
$ docker run --rm --entrypoint openssl lambci/lambda:provided version
OpenSSL 1.0.1k-fips 8 Jan 2015
```

Build environments have 1.0.2k:

```
$ docker run --rm --entrypoint openssl lambci/lambda:build-provided version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

Binaries compiled using this library fail when deployed to Lambda, as they look for version 1.0.2.

**Comment by mhart** [comment]
Ugh, yeah this was caused by Lambda updating glibc in the last few days – using a different yum repo from previously, so a lot of dev dependencies needed to also be updated – I guess openssl got caught up in this.

Will be something here – just need to figure out what's causing openssl to be updated: https://github.com/lambci/docker-lambda/compare/f48ff1f...4eaedc3

**Comment by mhart** [comment]
So `libssh2-devel` is the sticking point – dependencies of it rely on glibc-devel, as well as openssl-devel. However, the openssl version that's on the same repo as glibc-devel is 1.0.2k – so I somehow need to figure out how to update some of its dependencies from one repo and some from another. Nasty

**Comment by mhart** [comment]
This should be fixed now – thanks for reporting!
