### ISSUE TITLE
Ghostscript present in images but not on Lambda (2018.03)

### ISSUE THREAD

**Issue by taylor-zr** [lambci/docker-lambda#205]
When building a layer that uses Ghostscript, the binary and libraries are misleadingly present on the image:

```
docker run -it lambci/lambda:build-nodejs8.10 bash

which gs
   /usr/bin/gs
```

And as a sanity check on the Lambda environment, 

```
console.log(require('child_process').execSync('gs').toString())

{
      "errorType": "Error",
      "errorMessage": "Command failed: gs\n/bin/sh: gs: command not found\n",
}
```

**Comment by mhart** [comment]
You're looking at a build image – that has far more on it than a normal run image (and Lambda itself) because it's used for building dependencies. See https://github.com/lambci/docker-lambda#documentation for the list of yum packages installed on the build images.

You can see that it doesn't exist on the non-build image:

```
$ docker run -it --entrypoint which lambci/lambda:nodejs8.10 gs
which: no gs in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin)
```

**Comment by taylor-zr** [comment]
GhostScript being installed on a build machine doesn't make any sense -- can you explain the rationale here?

**Comment by mhart** [comment]
`yum install ImageMagick-devel` does it. `ImageMagick-devel` depends on `ghostscript-devel` and `ghostscript-devel` depends on `ghostscript`. You can contact Amazon Linux or RedHat if you want a rationale there.
