### ISSUE TITLE
lambci/lambda:nodejs10.x fails to set _X_AMZN_TRACE_ID properly

### ISSUE THREAD

**Issue by tdstein** [lambci/docker-lambda#222]
When using `lambci/lambda:nodejs10.x` the following WARN message is spammed by the logger:

```
_X_AMZN_TRACE_ID is missing required data.
```

This message is thrown by the `aws-sdk-xray-node` when `_X_AMZN_TRACE_ID` is not set or improperly formatted:

https://github.com/aws/aws-xray-sdk-node/blob/695f0498d3455a98c393d3720ee213384527f115/packages/core/lib/utils.js#L146

I am able to resolve the issue by setting the `_X_AMZN_TRACE_ID` environment variable to `Root=1-5759e988-bd862e3fe1be46a994272793;Parent=53995c3f42cd8ad8;Sampled=1`

This issue does not occur `lambci/lambda:nodejs8.10`. I have not tested any other Docker images.

**Comment by mhart** [comment]
It's set to a value similar to what the init process gets: https://github.com/lambci/docker-lambda/blob/master/base/base-2/Dockerfile#L24

The parser can't handle this for some reason.

There are a couple of routes I could take here – either modify it in the base image so that all runtimes get it – easier to do, but arguably "incorrect". Or, modify each runtimes itself. I think I'll go with the former 👍

**Comment by mhart** [comment]
Thanks for submitting! Should be all fixed now 🤞
