### ISSUE TITLE
general versioning question...

### ISSUE THREAD

**Issue by born2snipe** [lambci/docker-lambda#251]
What is the reasoning behind not publishing different versions of docker images as changes are made to the project?

For example I see the "nodejs8.10" image was updated a few days ago, but I do not see a new tag on DockerHub, but I do see the docker image was updated the same number days ago as the last commit to that mentioned code module.

The reason I am asking is we recently had a build failure in our CI pipeline because we got a new version of a docker image because we purged the images in the local registry to free up disk space. Maybe my docker-fu is not great or I am out of the loop of "best practices" for managing docker images. but do you have some recommendations/guidance on how to determine the previous revisions of a said docker image?

Thank you

**Comment by mhart** [comment]
The reasoning is that it's exactly what happens on production Lambdas – the same runtime name (eg, "nodejs8.10") can receive updates at any time – to the underlying OS, to the aws-sdk version, to the bootstrap. These images are then updated accordingly.

The only time I ever version it is when major refactor changes are made. See https://github.com/lambci/docker-lambda/issues/191#issuecomment-557824167 for more discussion

Can you explain the build failure you got a little more? Was it due to something in the image changing (and if so, did you run into the same problems in your production Lambdas)? Or was it just due to disk space running out?

**Comment by born2snipe** [comment]
We are currently using https://github.com/localstack/localstack which indirectly is using this docker container. The only thing that had changed is the changing of the this said docker image. The error we are receiving I am sure is specific to how localstack is interacting with this docker container.

I am more than happy trying to figure out what revision is causing the failure since it is only the last couple revisions, but I am currently assuming I will have to build those images on my machine to perform the triage since I am not aware of how to determine the `sha256` checksums of a past revision of a tagged docker image. If that is possible, I would be at least testing the images you built and not  my own where I could introducing a new variable in how the image was constructed.

**Comment by mhart** [comment]
Last I checked localstack was doing very specific things with the way they used these images.

Specifically, they've recently been changing the way they integrate with docker-lambda so that some runtimes are pinned to the version I mentioned in my previous comment and some are not (and this list has been changing): https://github.com/localstack/localstack/blob/f384f5837caad840201258a3d94e19d4bf68571f/localstack/services/awslambda/lambda_executors.py#L698-L706

If you still think the issue is with docker-lambda itself, please post the error here and I'll look into it.

**Comment by born2snipe** [comment]
We are getting the `2020/02/18 16:46:47 listen tcp :9001: bind: address already in use` for the `nodejs8.10` docker image. I have tried the following `localstack` versions: 0.10.6, 0.10.6, 0.10.7 and all fail with the same error mentioned.

The docker image of `lambci/docker-lambda` we found that works is the following: `lambci/lambda@sha256:bc59e063662af0e2ad2a634e0ca23e10a31ea1db12212da80aebf2ff2d9ee323`. I am not exactly sure how to back track that checksum back to the git commit on this repo, so hopefully you know something I don't on how to go about that. 🤞 

Yesterday I was originally hoping the [PR](https://github.com/localstack/localstack/pull/1861) would resolve the `port:9001` issue, but it did not.

Here are some of the environment variables passed to the docker image from `localstack`:

```
"Env": [
  "AWS_LAMBDA_EVENT_BODY=",
  "HOSTNAME=4f880b13c0a1",
  "LOCALSTACK_HOSTNAME=4f880b13c0a1",
  "NODE_ENV=localstack",
  "LOG_LEVEL=DEBUG",
  "AWS_LAMBDA_EVENT_BODY=...redacted...",
  "HOSTNAME=172.18.0.1",
  "LOCALSTACK_HOSTNAME=172.18.0.1",
  "AWS_LAMBDA_FUNCTION_TIMEOUT=300",
  "AWS_LAMBDA_FUNCTION_NAME=...redacted...",
  "AWS_LAMBDA_FUNCTION_VERSION=$LATEST",
  "AWS_LAMBDA_FUNCTION_INVOKED_ARN=...redacted...",
  "_LAMBDA_SERVER_PORT=5000",
  "PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
  "LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib",
  "LANG=en_US.UTF-8",
  "TZ=:UTC",
  "LAMBDA_TASK_ROOT=/var/task",
  "LAMBDA_RUNTIME_DIR=/var/runtime",
  "_LAMBDA_CONTROL_SOCKET=14",
  "_LAMBDA_SHARED_MEM_FD=11",
  "_LAMBDA_LOG_FD=9",
  "_LAMBDA_SB_ID=7",
  "_LAMBDA_CONSOLE_SOCKET=16",
  "_LAMBDA_RUNTIME_LOAD_TIME=1530232235231",
  "_AWS_XRAY_DAEMON_ADDRESS=169.254.79.2",
  "_AWS_XRAY_DAEMON_PORT=2000",
  "AWS_XRAY_DAEMON_ADDRESS=169.254.79.2:2000",
  "AWS_XRAY_CONTEXT_MISSING=LOG_ERROR",
  "_X_AMZN_TRACE_ID=Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1",
  "AWS_EXECUTION_ENV=AWS_Lambda_nodejs8.10",
],
"NODE_PATH=/opt/nodejs/node8/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task:/var/runtime/node_modules"
"Cmd": null,
"Image": "lambci/lambda:nodejs8.10",

```

**Comment by mhart** [comment]
It doesn't look like either `DOCKER_LAMBDA_API_PORT` or `DOCKER_LAMBDA_RUNTIME_PORT` is being passed to the docker container at all (like that PR suggests it would)

Basically the issue is that you're running multiple docker containers all trying to listen on the same port on the same host (probably because you're running the docker network in host mode?) Those env variables allow you to specify different ports so they don't clash.

This behaviour was introduced to docker-lambda in Nov 2019 – and all images were versioned at this time in case people needed to keep the old behaviour. See https://github.com/lambci/docker-lambda/issues/191 for more details. The `lambci/lambda:20191117-nodejs8.10` image contains the old code that does not expose this port in case you want to use that.

**Comment by born2snipe** [comment]
Thank you for your help today @mhart .
