### ISSUE TITLE
Wrong ImageMagick version

### ISSUE THREAD

**Issue by squeral** [lambci/docker-lambda#280]
I'm using `lambci/lambda:build-go1.x` to build my Lambda code but I noticed the installed version of ImageMagick is not the same running on Lambda.
```
Installed Packages (lambda)
ImageMagick.x86_64                 6.7.8.9-15.21.amzn1             @amzn-main
```
```
Installed Packages (lambci container)
ImageMagick.x86_64                 6.9.10.68-3.22.amzn1            @amzn-updates
ImageMagick-devel.x86_64           6.9.10.68-3.22.amzn1            @amzn-updates
```

**Comment by mhart** [comment]
You're right – it seems that the Lambda version has been held back, whereas the build image will install the latest available version of the devel tools: https://github.com/lambci/docker-lambda/blob/4143ed38a2882a45d6945085cb3895d142d1df11/base/build/Dockerfile#L20

I'll pin the version to prevent it from being updated. It's a little brittle to do it this way because yum requires exact version matching – so if the Lambda version updates even slightly, then the build version will need to be manually updated too

**Comment by mhart** [comment]
Done! You should find the correct version in the build images now:

```console
$ docker run --rm lambci/lambda:build-go1.x yum list installed | grep ImageMagick
ImageMagick.x86_64                 6.7.8.9-15.21.amzn1             @amzn-main   
ImageMagick-devel.x86_64           6.7.8.9-15.21.amzn1             @amzn-main   
```

**Comment by squeral** [comment]
Perfect! Thank you for the speedy fix.

**Comment by grizzly-monkey** [comment]
lambci/lambda:go1.x has 

```
yum list installed | grep ImageMagick
ImageMagick.x86_64                 6.9.10.68-3.22.amzn1            @amzn-updates
```


lambci/lambda:build-go1.x has 
```
bash-4.2# yum list installed | grep ImageMagick
ImageMagick.x86_64                 6.7.8.9-15.21.amzn1             @amzn-main   
ImageMagick-devel.x86_64           6.7.8.9-15.21.amzn1             @amzn-main
```

```
samcli/lambda:go1.x-02ea09868051f32e8da46c7ee has
bash-4.2$ yum list installed | grep ImageMagick
ImageMagick.x86_64                 6.9.10.68-3.22.amzn1            @amzn-updates
```

**Comment by mhart** [comment]
Sigh, looks like they finally updated the Lambda versions. This should be fixed in the latest docker-lambda versions @grizzly-monkey
