### ISSUE TITLE
Remove default AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env vars

### ISSUE THREAD

**Issue by simonvanderveldt** [lambci/docker-lambda#31]
First of all thanks for this project. Pretty useful to have :)

Would it be possible to remove the default `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env vars from the images that that are for example defined here https://github.com/lambci/docker-lambda/blob/4e9ae90ab36cb3e686361ea1f29e496c7d0bf966/python3.6/run/runtime-mock.py#L33

I'd like to check/give feedback from the lambda I'm running if these are set and error if they aren't, but currently can't do so because these default are there.

**Comment by mhart** [comment]
@simonvanderveldt but they're *always* set on AWS Lambda

**Comment by simonvanderveldt** [comment]
@mhart Yeah, but that's not the case when running them locally in Docker :)
This is mainly meant for our CI since we want to automatically validate the Lambda's we write

**Comment by mhart** [comment]
@simonvanderveldt but then I'm not sure what you mean by "validate the Lambdas we write"?

The variable is always set on AWS Lambda and this docker image / test runner is trying to replicate that environment as closely as possible

**Comment by mhart** [comment]
Trying to understand the use case – is it because you've added this check to your Lambda fn and you're trying to get coverage on it, or something similar to this?

If so, then I think the check itself (or at least, trying to get 100% coverage on it) is suspect. It's akin to checking whether the `event` arg exists, or whether the `context` arg has a `get_remaining_time_in_millis` property on it, and checking whether it's a function or not. You certainly *could* add these checks, but you really shouldn't. If these things aren't set, then there are much bigger problems 😉

If this isn't the case you're trying to add this option for, then I think I still don't fully understand the use case

**Comment by mhart** [comment]
Closing this – let me know if I've misunderstood your use case somehow
