### ISSUE TITLE
executing a query on a SQLite file into lambda function error:  No module named '_sqlite3' 

### ISSUE THREAD

**Issue by AndresUrregoAngel** [lambci/docker-lambda#81]
Hello everyone, 

One of the methods in my code uses the library `sqlalchemy` to perform a bunch of queries in a local SQLite file.

Before my deployment for sure, I download any dependency and stored in the folder where I`m running my lambda test. For instance for SQLAlchemy I did `pip3 install module-name -t /path/to/project-dir`
My import looks like:

```
# _*_ coding:utf-8 _*_
#!/usr/bin/env python3
import pymysql as db
from sqlalchemy.sql import text
import logging
import psycopg2
from sqlalchemy import create_engine
from md_errorhandler import *
import inspect
```

And then the method that reaches outs the SQLite file and executes an input query looks:

```
def sqlite_exec_query(query_text):

    try:
        engine = create_engine('sqlite:///mtm-etl.sql')
        query = text(query_text)
        result = engine.execute(query)
        for row in result:
            query_output = row[0]
    except Exception as e:
        logging.info(e)
        logging.info(e)
        method = inspect.stack()[0].function
        send_notification(e, method)

    else:
        return query_output
```

When I execute my docker image with :  `docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6 python_file.lambda_handler`

I get this output:
```
START RequestId: c435af66-c32d-40b7-bbe5-c3ad47090c96 Version: $LATEST
Unable to import module 'md_executor_update': No module named '_sqlite3'
END RequestId: c435af66-c32d-40b7-bbe5-c3ad47090c96
REPORT RequestId: c435af66-c32d-40b7-bbe5-c3ad47090c96 Duration: 1477 ms Billed Duration: 1500 ms Memory Size: 1536 MB Max Memory Used: 36 MB

{"errorMessage": "Unable to import module 'python_file'"}
```
Thanks so much

**Comment by ozskywalker** [comment]
Before jumping into all of this - is there a design decision that's driven you to consume SQLite inside of a lambda function, instead of an external DB service?

**Comment by AndresUrregoAngel** [comment]
This process is designed to move to redshift few S3 bucket files and then execute a bunch of queries such as DELETE/INSERT and so on.  The purpose of the SQLite file is to contain a table with a library queries and each time that my function requires to execute certain queries based in parameters would be able to reach them out locally in the SQLite file. this is why. Do you know if work with SQLite files is not allowed in lambda functions?

**Comment by ozskywalker** [comment]
Referencing issue #36 - if you want to use sqlite, you'll need to bundle in the python library as it's lacking in the Amazon Linux AMI used by Lambda.   But keep in mind that the container runs on ephemeral storage - so while you can package a .sql file into the lambda upload, it's not going to maintain state between each execution of your lambda function.

AFAIR - you're not restricted by files, but you are restricted by the size of your lambda function - 50mb compressed / 250mb uncompressed.   So if it's under that limit, you could package it in then open it from /var/task/.

But if it's larger than that, or you want to write state into it, then it would make more sense to either store this data in RDS, or a S3 file (and download it to /tmp).

As for bundling in - maybe someone's written a better guide out there, but I put together a very-very-rough build script for doing this in a test project myself over here because I needed NLTK in my lambda function -> https://github.com/ozskywalker/minerva/blob/master/worker_Articles/build_lambda_zip.sh

Doing this however may increase the cold startup & execution times for your function - in your shoes I'd have a bias towards leveraging existing supported libraries where possible for maximum optimization.

**Comment by AndresUrregoAngel** [comment]
Dear god Mr @ozskywalker  that looks pretty much complicated and extensive/expensive in terms of time work. So probably I would be able to create this query library in a Redshift or RDS table to read it directly from there rather than and SQLite. I will perform few of PoC and then I`ll back ! thanks

**Comment by tdmalone** [comment]
This doesn't work on Lambda in general, correct? In which case it, correctly, shouldn't work on docker-lambda either. ;)

**Comment by mhart** [comment]
@tdmalone – it would work on Lambda (and docker-lambda) – although I agree with some of the others that it's not an ideal use case for Lambda.

@AndresUrregoAngel – I'd also look at using [Athena](https://aws.amazon.com/athena/) for some of your S3 querying needs – you can use that from Lambda too.
